#!/usr/bin/env bash

# some more ls aliases
alias l='ls -all -lF -S -h'
alias la='ls -A'
alias ll='ls -CF'
alias listdir='ls -l -d */'
alias listdirsize='du -sh -- *'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias findt='find . -name $1'
alias grept='grep -IRni $1'
alias wget='wget -c'

# set some other defaults
alias df='df -H'
alias du='du -ch'

# top is atop, just like vi is vim
alias top='atop'

# list all open TCP/UDP port
alias ports='netstat -tulanp'

## shortcut for iptables and pass it via sudo
alias ipt='sudo /sbin/iptables'

# display all rules
alias iptlist='sudo /sbin/iptables -L -n -v --line-numbers'
alias iptlistin='sudo /sbin/iptables -L INPUT -n -v --line-numbers'
alias iptlistout='sudo /sbin/iptables -L OUTPUT -n -v --line-numbers'
alias iptlistfw='sudo /sbin/iptables -L FORWARD -n -v --line-numbers'
alias firewall=iptlist

# get web server headers
alias header='curl -I'

# find out if remote server supports gzip / mod_deflate or not
alias headerc='curl -I --compress'

# All of our servers specified interface is connected
# to the internets via vlan / router etc
alias dnstop='sudo dnstop -l 5'
alias vnstat='sudo vnstat -i'
alias iftop='sudo iftop -i'
alias tcpdump='sudo tcpdump -i'
alias ethtool='sudo ethtool'

## pass options to free ##
alias meminfo='free -m -l -t'

## get top process eating memory
alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'

## get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3'
alias pscpu10='ps auxf | sort -nr -k 3 | head -10'

## list zombie processes
alias pszombie="ps afuwwx | less +u -p'^(\S+\s+){7}Z.*'"
#alias pidzombie="ps aux | awk '{ print $8 " " $2 }' | grep -w Z | cut -d ' ' -f 2"

## Get server cpu info ##
alias cpuinfo='lscpu'

## older system use /proc/cpuinfo ##
##alias cpuinfo='less /proc/cpuinfo' ##

## get GPU ram on desktop / laptop##
alias gpumeminfo='grep -i --color memory /var/log/Xorg.0.log'
alias rr='cd "$(git rev-parse --show-toplevel 2>/dev/null)"'

#alias encrypt_pass='echo "${1}" | gpg --symmetric | base64'
alias rgn='rg --no-ignore'
#alias pdftk='pdftk ${1} output ${2} userpw ${3}'

#Show my ip address
alias myip="curl http://ipecho.net/plain; echo"

#Show my local ip addresses
alias mylocalip="ip -4 addr | grep -oP '(?<=inet\s)\d+(\.\d+){3}'"

#docker
alias dockerpsf='docker ps --format "table {{.Image}}\t{{.Ports}}\t{{.Names}}"'

alias tmux-save-pane='tmux capture-pane -pS -'

[ -f ~/.bash_custom_aliases ] && source ~/.bash_custom_aliases
