STARDICT_DATA_DIR="$(HOME)/.stardict/dic"

all:
	mkdir -p $(STARDICT_DATA_DIR)
	tar -xvf stardict-oald-2.4.2.tar.bz2 -C $(STARDICT_DATA_DIR)
	tar -xvf stardict-freedict-eng-tur-2.4.2.tar.bz2 -C $(STARDICT_DATA_DIR)
